#---------- Base limpio --------------
x-base: &base
  build: .
  image: orquestador
  networks:
    - orchestrator_network
  restart: always
#---------- Base con docker.sock -----
x-docker: &docker
  <<: *base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#---------- Base con sync ------------
x-sync: &sync
  <<: *docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#-------- Produccion ----------------
x-env-prod: &env-prod
  <<: *docker
  env_file:
    - ./Codigo/Env/produccion.env
#-------- Desarrollo -----------------
x-env-dev: &env-dev
  <<: *docker
  env_file:
    - ./Codigo/Env/desarrollo.env
#----------------------------------

services:

  it_orchestrator:
    <<: [ *sync, *env-prod ]
    container_name: it_orchestrador
    profiles: [ "it" ]
    ports:
      - "9090:8080"
    volumes:
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/it.py

  webhook_webCorredor:
    <<: [ *sync, *env-dev ]
    container_name: webhook_webCorredor
    profiles: [ "webCorredor" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Webhook/webhook_webCorredor.py

  ejecutivo_orchestrator:
    <<: [ *env-prod ]
    container_name: ejecutivo
    profiles: [ "ejecutivo" ]
    ports:
      - "6060:8080"
    volumes:
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/ejecutivo.py

  jishu_orchestrator:
    <<: [ *env-prod ]
    container_name: jishu_orchestrador
    profiles: [ "jishu" ]
    ports:
      - "8080:8080"
    volumes:
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/jishu.py

  webhook_cotizador:
    <<: [ *sync, *env-dev ]
    container_name: webhook_cotizador
    profiles: [ "cotizador" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Webhook/webhook_cotizador.py

  redis:
    image: redis:7
    profiles: [ "redis" ]
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - orchestrator_network
    restart: always

volumes:
  redis_data:

networks:
  orchestrator_network:
    name: orchestrator_network
    external: true # (indicado que ya existe)

# Primero crear imagen chromedriver : docker build -f ChromeDriver.base -t chromedriver:stable .
# Segundo crear imagen playwright : docker build -f Playwright.base -t playwright-base:1.0 .
# Crear imagen orquestador :  docker build --no-cache -t orquestador .
# Crear imagen Web Corredor : docker build --no-cache -t web_corredor .
# Crear imagen Web Cotizador (Rimac) : docker build --no-cache -t cotizador .
# Crear imagen Web Cotizador (Positiva) : docker build --no-cache -t cotizacion_positiva .