#---------- Base común para servicios orquestadores ----------
x-service-base: &service-base
  build: .
  image: orquestador
  restart: always
  networks:
    - orchestrator_network
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./Codigo:/app/Codigo
  dns:
    - 8.8.8.8
    - 1.1.1.1

services:

  it_orchestrator:
    <<: *service-base
    container_name: it_orchestrador
    profiles: [ "it" ]
    ports:
      - "9090:8080"
    command: python3 Codigo/Ejecutivos/it.py

  webhook_webCorredor:
    <<: *service-base
    container_name: webhook_webCorredor
    profiles: [ "webCorredor" ]
    command: python3 Codigo/Webhook/webhook_webCorredor.py

  ejecutivo_orchestrator:
    <<: *service-base
    container_name: ejecutivo
    profiles: [ "ejecutivo" ]
    ports:
      - "6060:8080"
    command: python3 Codigo/Ejecutivos/ejecutivo.py

  jishu_orchestrator:
    <<: *service-base
    container_name: jishu_orchestrador
    profiles: [ "jishu" ]
    ports:
      - "8080:8080"
    command: python3 Codigo/Ejecutivos/jishu.py

  webhook_cotizador:
    <<: *service-base
    container_name: webhook_cotizador
    profiles: [ "cotizador" ]
    command: python3 Codigo/Webhook/webhook_cotizador.py

  redis:
    image: redis:7
    profiles: [ "redis" ]
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - orchestrator_network
    restart: always

volumes:
  redis_data:

networks:
  orchestrator_network:
    name: orchestrator_network
    external: true # (indicado que ya existe)

# Primero crear imagen chromedriver : docker build -f ChromeDriver.base -t chromedriver:stable .
# Segundo crear imagen playwright : docker build -f Playwright.base -t playwright-base:1.0 .
# Crear imagen orquestador :  docker build --no-cache -t orquestador .
# Crear imagen Web Corredor : docker build --no-cache -t web_corredor .
# Crear imagen Web Cotizador (Rimac) : docker build --no-cache -t cotizador .
# Crear imagen Web Cotizador (Positiva) : docker build --no-cache -t cotizacion_positiva .

# docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile cotizador --profile webCorredor --profile redis up -d
# docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile "*" up -d
# docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile "*" down

# docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile it --profile jishu --profile redis up -d
# docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile "*" up -d
# docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile "*" down
