#---------- Base limpio --------------
x-base: &base
  build: .
  image: orquestador
  networks:
    - orchestrator_network
  restart: always
#---------- Base con docker.sock --------------
x-docker: &docker
  <<: *base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#---------- Base con sync --------------
x-sync: &sync
  <<: *docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - rutas_sync:/app/sync
#-------- PRODUCCION --------------
x-env-prod: &env-prod
  <<: *docker
  env_file:
    - ./env/produccion.env
#-------- DESARROLLO--------------
x-env-dev: &env-dev
  <<: *docker
  env_file:
    - ./env/desarrollo.env
#----------------------------------

services:

  it_orchestrator:                  
    <<: [*sync, *env-prod]
    container_name: it_orchestrador
    profiles: ["it"]
    volumes:
      - mapfre_codigo:/codigo_mapfre
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/IT/it.py

  webhook_webCorredor:
    <<: [*sync, *env-prod]
    container_name: webhook_webCorredor
    profiles: ["webCorredor"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rutas_sync:/app/sync
      - ./env:/app/env
      - mapfre_codigo:/codigo_mapfre
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Webhook/webhook_webCorredor.py

  ejecutivo_orchestrator:
    <<: [*env-prod]
    container_name: ejecutivo
    profiles: ["ejecutivo"]
    volumes:
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/ejecutivo.py

  jishu_orchestrator:
    <<: [*env-prod]
    container_name: jishu_orchestrador
    user: root
    profiles: ["jishu"]
    volumes:
      - rimac_SAS:/codigo_rimac_SAS
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Ejecutivos/jishu.py

  webhook_cotizador:
    <<: [*sync, *env-prod]
    container_name: webhook_cotizador
    user: root
    profiles: ["cotizador"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rutas_sync:/app/sync
      - ./env:/app/env
      - rimac_SAS:/codigo_rimac_SAS
      - ./Codigo:/app/Codigo
    command: python3 Codigo/Webhook/webhook_cotizador.py

# Podemos declarar infinito volumens, pero solo se crea el que se use en algun servicio, si no se usa, no se crea, aunque este declarado
volumes:
  mapfre_codigo:
    name: mapfre_codigo
  rutas_sync:                   
    name: rutas_sync          
  # pacifico_codigo:              
  #   name: pacifico_codigo
  # rimac_Web:                    
  #   name: rimac_Web
  rimac_SAS:                    
    name: rimac_SAS

# external:True (indicado que ya existe) o sino (docker volume create "nombre")
networks:
  orchestrator_network:         
    name: orchestrator_network
    external: true
    
# Comandos : 
# docker compose up -d --build --> Crea y levanta los servicios del docker-compose.yml,reconstruyendo las imagenes si hay cambios en el Dockerfile, requeriments(Dependencias) o en el contexto de build.
# docker-compose down          --> Apaga y elimina todo lo que fue creado por ese docker-compose.yml (Preferible si hay cambios en variables de entorno)
# docker-compose up -d         --> Crea y levanta los servicios definidos en el docker-compose.yml
# docker-compose restart

# docker build --no-cache -t orquestador .